### ISSUE TITLE
Invalid workflow file for code quality scan action

### ISSUE THREAD

**Issue by BryceMehring** [bayer-int/.github#5]
I'm getting the following error when trying to run the code quality scan action:

```
Invalid workflow file : .github/workflows/code-quality.yml#L18
The workflow is not valid. .github/workflows/code-quality.yml (Line: 18, Col: 15): Expected format {org}/{repo}[/path]@ref. Actual 'docker pull --quiet $CODECLIMATE_VERSION' Input string was not in a correct format.
```

**Comment by timmeinerzhagen** [comment]
Hi yeah i noticed that too, I shot you a private message.
It is best not to discuss internal topics via issues within this repository, since this repo specifically has to be set to PUBLIC for everybody. Otherwise the defined templates don't show up for anybody.
